---
- name: 'Check mandatory variables are defined'
  assert:
    that:
      - static_ip is defined
      - router_ip is defined

- name: Configure nginx site
  template:
    src: dhcpcd.j2
    dest: "/etc/dhcpcd.conf"
    owner: root
    group: root
    mode: '0644'
