---
- name: 'Check mandatory variables are defined'
  assert:
    that:
      - static_ip is defined
      - router_ip is defined

- name: Setup static ip
  notify: Restart dhcpcd service
  template:
    src: dhcpcd.j2
    dest: "/etc/dhcpcd.conf"
    owner: root
    group: root
    mode: '0644'
    register: dhcpcd_configuration

- name: Restart dhcpcd service
  systemd:
    state: restarted
    daemon_reload: true
    name: dhcpcd
